# Local mirror of CI. `just` alone runs everything; each recipe also works on
# its own. CI calls `just check`, so there is one definition of "green".

default: check

# Everything CI runs, in the same order.
check: windows-bootstrapper ui-build fmt-check clippy ui-bindings-check test doc gates deny ui-check ui-test

# The Rust checks and the UI checks together.
check-all: check

fmt:
    cargo fmt --all

fmt-check:
    cargo fmt --all -- --check

clippy:
    cargo clippy --workspace --all-targets --all-features --locked -- -D warnings

test:
    cargo test --workspace --all-features --locked

doc:
    RUSTDOCFLAGS="-D warnings" cargo doc --workspace --no-deps --all-features --locked

deny:
    cargo deny --locked check

# The UI: types generated by the Rust tests, then svelte-check and a build.
ui-install:
    cd ui && npm ci

ui-check:
    cd ui && node scripts/barrel.mjs && npm run check

ui-test:
    cd ui && npm test

# Export into a temporary directory and compare before tests can rewrite files.
ui-bindings-check:
    node ui/scripts/check-bindings.mjs

ui-build:
    cd ui && npm run build

# One native application with its UI, fonts, material artwork and license texts.
standalone: windows-bootstrapper ui-build
    cargo build --release -p openlaser --features desktop --locked

# Release binaries for every target, with home-folder paths removed.
release-build:
    python3 scripts/build_release.py

# Windows builds fetch the verified Microsoft installer locally, outside Git.
windows-bootstrapper:
    node scripts/prepare-webview2.mjs

# Hot reload against `openlaser --simulate` on port 8080.
ui-dev:
    cd ui && npm run dev

# Repository rules that no compiler enforces.
gates: gate-names gate-layers

# The retired prototype's identifiers must not leak into the public tree.
gate-names:
    #!/usr/bin/env bash
    set -euo pipefail
    if git grep -iIn -e 'nex[c]ut[-_]' -e 'nex[c]ut studio' -- ':!Cargo.lock'; then
        echo "gate-names: prototype identifier found"; exit 1
    fi
    echo "gate-names: ok"

# The synchronous crates never pull in an async runtime or a network stack.
gate-layers:
    #!/usr/bin/env bash
    set -euo pipefail
    for crate in core correction prep nest dxf svg xml protocol compiler library network; do
        if cargo tree --locked -p "openlaser-$crate" -e normal --prefix none \
            | grep -qE '^(tokio|async-std|axum|hyper|mio|reqwest) '; then
            echo "gate-layers: openlaser-$crate depends on an async or network crate"; exit 1
        fi
    done
    echo "gate-layers: ok"
