// Writes src/api/index.ts re-exporting every binding ts-rs generated, so
// the app imports one module and no type is written by hand.
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { bindingText } from './binding-format.mjs';

const dir = new URL('../src/api/bindings/', import.meta.url);
const names = readdirSync(dir).filter(f => f.endsWith('.ts')).map(f => f.slice(0, -3)).sort();
for (const name of names) {
  const file = new URL(`${name}.ts`, dir);
  const raw = readFileSync(file, 'utf8'), normalized = bindingText(raw);
  if (raw !== normalized) writeFileSync(file, normalized);
}
const lines = names.map(n => `export type { ${n} } from './bindings/${n}';`);
writeFileSync(new URL('../src/api/index.ts', import.meta.url), `// Generated by scripts/barrel.mjs from the ts-rs bindings. Do not edit.\n${lines.join('\n')}\n`);
console.log(`${names.length} bindings`);
