// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An adapter as the operator sees it.
 */
export type AdapterView = {
/**
 * The interface name.
 */
name: string,
/**
 * What the computer calls the hardware.
 */
description: string,
/**
 * Its addresses.
 */
addresses: Array<string>, };
