// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResetRecord } from "./ResetRecord";

/**
 * One alarm's occurrences during an application session.
 */
export type AlarmRecord = { 
/**
 * Stable source and native ID, independent of the translated label.
 */
key: string, 
/**
 * Native alarm ID, if available.
 */
id: number | null, 
/**
 * Where the alarm was observed.
 */
source: string, 
/**
 * Latest plain name, as operators read it.
 */
label: string, 
/**
 * First trip in seconds since the epoch.
 */
first: number, 
/**
 * Most recent trip.
 */
last: number, 
/**
 * Distinct inactive-to-active transitions.
 */
count: number, 
/**
 * Last observed recovery, if any. Restart does not imply recovery.
 */
recovered: number | null, 
/**
 * Whether the cause was present at the last observation in this session.
 */
active: boolean, 
/**
 * Most recent reset attempt for this row.
 */
reset: ResetRecord | null, };
