// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AlarmRecord } from "./AlarmRecord";

/**
 * Alarms grouped under one application restart separator.
 */
export type AlarmSession = {
/**
 * File schema version.
 */
version: number,
/**
 * Unique application start ID and pagination cursor.
 */
id: string,
/**
 * Application start time in seconds since the epoch.
 */
started: number,
/**
 * Alarm summaries; their active state is historical for earlier sessions.
 */
alarms: Array<AlarmRecord>, };
