// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReliefView } from "./ReliefView";

/**
 * One alarm row.
 */
export type AlarmView = {
/**
 * Whether the cause is present, distinct from retained reset state.
 */
active: boolean,
/**
 * The actual relief offered for this row, shown before activation.
 */
relief: ReliefView,
/**
 * The vendor's id, when it emits one.
 */
id: number | null,
/**
 * Where the row came from.
 */
source: string,
/**
 * The vendor's label, or the host rule's.
 */
label: string,
/**
 * The plain name operators read, such as "Emergency stop pressed".
 */
title: string,
/**
 * One sentence on how to clear the row.
 */
fix: string,
/**
 * Whether the row blocks operations.
 */
blocking: boolean,
/**
 * Whether the row stays until relieved even when the cause is gone.
 */
latched: boolean,
/**
 * Seconds since the row appeared.
 */
age_seconds: number, };
