// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The point of the placed part the job origin stands for: one of the
 * nine positions on its bounds, as the vendor's docking point.
 */
export type Anchor = "front_left" | "front_center" | "front_right" | "left" | "center" | "right" | "back_left" | "back_center" | "back_right";
