// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LaserMode } from "./LaserMode";
import type { RecipeSummary } from "./RecipeSummary";

/**
 * One layer bank of the machine files.
 */
export type BankView = {
/**
 * Which laser.
 */
laser: LaserMode,
/**
 * The bank, 1 to 11.
 */
bank: number,
/**
 * The vendor's `LayerFileName`, often the material it was saved from.
 */
name: string,
/**
 * Whether the vendor disabled it.
 */
disabled: boolean,
/**
 * Its headline values.
 */
summary: RecipeSummary, };
