// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LaserMode } from "./LaserMode";
import type { OutputsView } from "./OutputsView";
import type { RuleView } from "./RuleView";

/**
 * The bound machine, as the UI needs it.
 */
export type BindingsView = { 
/**
 * The laser the bindings are for.
 */
mode: LaserMode, 
/**
 * Whether a head controller is configured.
 */
head_enabled: boolean, 
/**
 * Slow and fast jog speeds in millimetres per second.
 */
jog_speed: [number, number], 
/**
 * The lifting table's positive travel limit, when that branch is configured.
 */
table_maximum_mm: number | null, 
/**
 * The travel of X and Y in millimetres, lower then upper.
 */
extent: [[number, number], [number, number]], 
/**
 * Which manual outputs are assigned.
 */
outputs: OutputsView, 
/**
 * The host input rules, for the alarm list.
 */
rules: Array<RuleView>, };
