// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Point } from "./Point";

/**
 * An axis-aligned box.
 */
export type Bounds = { 
/**
 * The lowest X and Y.
 */
min: Point, 
/**
 * The highest X and Y.
 */
max: Point, };
