// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Bridge } from "./Bridge";
import type { Millimeters } from "./Millimeters";

/**
 * Bridges: two contours joined through a channel so they cut as one.
 */
export type Bridges = {
/**
 * The channel width.
 */
width: Millimeters,
/**
 * The connections, applied in order.
 */
connections: Array<Bridge>, };
