// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Pick } from "./Pick";

/**
 * One bridge, between two picked points.
 */
export type Bridge = { 
/**
 * One end.
 */
first: Pick, 
/**
 * The other end.
 */
second: Pick, };
