// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Bar } from "./Bar";
import type { Liters } from "./Liters";
import type { Nozzle } from "./Nozzle";

/**
 * A saved 60-second flow test: the measured over the estimated volume.
 */
export type Calibration = {
/**
 * Measured litres over estimated litres; multiplies every estimate.
 */
factor: number,
/**
 * When it was measured, in seconds since the epoch.
 */
at: number,
/**
 * The test pressure.
 */
pressure: Bar,
/**
 * The nozzle fitted for the test.
 */
nozzle: Nozzle,
/**
 * What the uncalibrated model expected over the test.
 */
estimated: Liters,
/**
 * What the operator measured.
 */
measured: Liters, };
