// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Quality } from "./Quality";

/**
 * Calibration status for the material selected in the current job.
 */
export type CalibrationView = {
/**
 * The quality of a completed calibration on this connection.
 */
quality: Quality | null,
/**
 * That calibration still applies to the current material and bindings.
 */
current: boolean, };
