// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An execution checkpoint.
 */
export type CheckpointView = {
/**
 * The item tag being executed.
 */
item: number,
/**
 * Progress within the item.
 */
progress: number,
/**
 * X and Y where the machine stopped, in millimetres.
 */
position_mm: [number, number], };
