// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CheckAction } from "./CheckAction";

/**
 * A short operator check, optionally with an explicitly invoked setup action.
 */
export type Check = {
/**
 * Text beside the checkbox.
 */
text: string,
/**
 * An available action; never executed by checking the box.
 */
action: CheckAction | null,
/**
 * Check automatically only while the current state satisfies the action.
 */
auto_check: boolean, };
