// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a held program stopped within the current remainder.
 */
export type Checkpoint = { 
/**
 * Pass index in this execution, distinct from its original ordinal.
 */
pass: number, 
/**
 * Distance fraction of its execution path; a point is before or after.
 */
fraction: number, };
