// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Check } from "./Check";

/**
 * A mode's default checklist.
 */
export type Checklist = {
/**
 * Whether the checks are required before Start.
 */
enabled: boolean,
/**
 * Checks in display order.
 */
steps: Array<Check>, };
