// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Anchor } from "./Anchor";

/**
 * The only machine operations a checklist can offer.
 */
export type CheckAction = { "kind": "home", } | { "kind": "origin", } | { "kind": "set_origin", } | { "kind": "set_origin_at",
/**
 * Point on both the job and bed bounds.
 */
point: Anchor, } | { "kind": "move_to",
/**
 * Point on the bed bounds.
 */
point: Anchor, } | { "kind": "move_xy",
/**
 * X coordinate in millimetres.
 */
x: number,
/**
 * Y coordinate in millimetres.
 */
y: number, } | { "kind": "calibrate", } | { "kind": "job_gas_test",
/**
 * Maximum time for each test, 50 to 2000 milliseconds.
 */
duration_ms: number, } | { "kind": "gas_test",
/**
 * Native gas selector, 0 to 5.
 */
selector: number,
/**
 * Pressure in bar for a proportional valve.
 */
pressure: number,
/**
 * Maximum on time, 50 to 2000 milliseconds.
 */
duration_ms: number, };
