// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Selected contours whose shared spans can be cut once.
 */
export type CommonEdges = { 
/**
 * Placed contour identities, before bridges.
 */
contours: Array<number>, 
/**
 * Maximum separation for equivalent spans, in millimetres.
 */
tolerance: number, 
/**
 * Permit retracing a shared span to connect remaining cuts on one contour.
 */
allow_overcut: boolean, };
