// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Move } from "./Move";
import type { PassView } from "./PassView";
import type { Usage } from "./Usage";

/**
 * The compiled program, summarised.
 */
export type Compiled = {
/**
 * Whether it is a dry run.
 */
dry_run: boolean,
/**
 * The predictable duration in seconds.
 */
seconds: number,
/**
 * Every pass, including its original identity after a continuation.
 */
plan: Array<PassView>,
/**
 * Where each pass pierces or starts, in drawing coordinates.
 */
pierces: Array<[number, number]>,
/**
 * How many upload blocks.
 */
blocks: number,
/**
 * The travel and cut moves for the run page, in drawing coordinates.
 */
moves: Array<Move>,
/**
 * Laser time, gas time, pierces and cut length of one run.
 */
usage: Usage, };
