// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The connection to the controller.
 */
export type Connection = { "state": "disconnected" } | { "state": "connected",
/**
 * The connection count.
 */
epoch: number,
/**
 * The endpoint.
 */
endpoint: string, } | { "state": "faulted",
/**
 * Why.
 */
reason: string, };
