// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GasLine } from "./GasLine";
import type { Millimeters } from "./Millimeters";
import type { Money } from "./Money";
import type { Nozzle } from "./Nozzle";
import type { Seconds } from "./Seconds";

/**
 * A job's or run's laser time, gas and cost.
 */
export type Consumption = { 
/**
 * Laser-on time.
 */
laser: Seconds, 
/**
 * Pierces.
 */
pierces: number, 
/**
 * Length cut.
 */
cut: Millimeters, 
/**
 * The nozzle the recipe fits, if it names one.
 */
nozzle: Nozzle | null, 
/**
 * Gas by gas and pressure.
 */
gases: Array<GasLine>, 
/**
 * The total gas cost, when every gas used is priced.
 */
cost: Money | null, };
