// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Curve } from "./Curve";

/**
 * A chain of curves on one drawing layer.
 */
export type Contour = { 
/**
 * The drawing layer the contour came from.
 */
layer: string, 
/**
 * The curves, each starting where the previous one ends.
 */
curves: Array<Curve>, };
