// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoolingPlacement } from "./CoolingPlacement";
import type { Milliseconds } from "./Milliseconds";

/**
 * Cooling stops: the head waits with the laser off.
 */
export type Cooling = {
/**
 * How long each stop lasts.
 */
dwell: Milliseconds,
/**
 * Where the stops go.
 */
placement: CoolingPlacement, };
