// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Degrees } from "./Degrees";
import type { Spot } from "./Spot";

/**
 * Where cooling stops go.
 */
export type CoolingPlacement = { "automatic": { 
/**
 * A stop where the contour starts.
 */
at_start: boolean, 
/**
 * A stop at every corner sharper than this interior angle.
 */
corners_below: Degrees | null, } } | { "manual": Array<Spot> };
