// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Bounds } from "./Bounds";
import type { LaserMode } from "./LaserMode";
import type { Measurement } from "./Measurement";
import type { Profile } from "./Profile";

/**
 * Current measurements and the profile that new DXF jobs will receive.
 */
export type CorrectionView = { 
/**
 * Concurrency token for saving this form.
 */
revision: number, 
/**
 * Laser being calibrated.
 */
mode: LaserMode, 
/**
 * Current machine dimensions.
 */
bed: Bounds, 
/**
 * Coupon centres in bottom-to-top row order.
 */
positions: [[number, number], [number, number], [number, number], [number, number], [number, number], [number, number], [number, number], [number, number], [number, number]], 
/**
 * Measurements for this bed; unfinished cells are null.
 */
measurements: [Measurement | null, Measurement | null, Measurement | null, Measurement | null, Measurement | null, Measurement | null, Measurement | null, Measurement | null, Measurement | null], 
/**
 * Applied snapshot, which may belong to an older bed.
 */
active: Profile | null, 
/**
 * Automatically apply the active snapshot to new DXF jobs.
 */
enabled: boolean, };
