// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LaserMode } from "./LaserMode";
import type { Measurement } from "./Measurement";

/**
 * Save a partial measurement set, apply a complete one, or pause future use.
 */
export type CorrectionChange = { "action": "measure", 
/**
 * Current form revision.
 */
revision: number, 
/**
 * Which laser was measured.
 */
mode: LaserMode, 
/**
 * Nine effective X/Y measurements, with empty cells allowed while editing.
 */
measurements: [Measurement | null, Measurement | null, Measurement | null, Measurement | null, Measurement | null, Measurement | null, Measurement | null, Measurement | null, Measurement | null], 
/**
 * Enable after validating all nine cells.
 */
apply: boolean, } | { "action": "enable", 
/**
 * Current form revision.
 */
revision: number, 
/**
 * Which laser to change.
 */
mode: LaserMode, 
/**
 * Whether to use the active profile.
 */
enabled: boolean, };
