// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A gas volume at standard conditions, as suppliers bill it.
 */
export type CubicMeters = number;
