// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Point } from "./Point";

/**
 * A line or an arc.
 */
export type Curve = { "type": "line",
/**
 * Where it starts.
 */
start: Point,
/**
 * Where it ends.
 */
end: Point, } | { "type": "arc",
/**
 * The centre.
 */
center: Point,
/**
 * The radius.
 */
radius: number,
/**
 * The angle of the start point, in radians.
 */
start_angle: number,
/**
 * The signed angle swept, in radians; negative is clockwise.
 */
sweep: number, };
