// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OrderStrategy } from "./OrderStrategy";

/**
 * The cutting order.
 */
export type CutOrder = { 
/**
 * The base order.
 */
strategy: OrderStrategy, 
/**
 * Cut holes before the outline around them.
 */
inner_first: boolean, 
/**
 * Cut circles before other shapes.
 */
circles_first: boolean, 
/**
 * Keep consecutive cuts apart to spread heat.
 */
spread_heat: boolean, };
