// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BindingsView } from "./BindingsView";
import type { CalibrationView } from "./CalibrationView";
import type { DraftView } from "./DraftView";
import type { ExecutionView } from "./ExecutionView";
import type { FilesView } from "./FilesView";
import type { HistoryStatus } from "./HistoryStatus";
import type { LaserMode } from "./LaserMode";
import type { LibraryView } from "./LibraryView";
import type { LinkView } from "./LinkView";
import type { Message } from "./Message";
import type { PostflightNotice } from "./PostflightNotice";
import type { ProgressView } from "./ProgressView";
import type { Readiness } from "./Readiness";
import type { RecoveryView } from "./RecoveryView";
import type { SoftView } from "./SoftView";
import type { State } from "./State";

/**
 * The whole state, as JSON.
 */
export type Document = { 
/**
 * Most recent completed sheet; history geometry loads on demand.
 */
completed_sheet: string | null, 
/**
 * Retained original execution and recovery choices.
 */
recovery: RecoveryView | null, 
/**
 * Retained authoring edits that could not be written to disk.
 */
persistence_error: string | null, 
/**
 * Revision of persisted preflight defaults.
 */
preflight_revision: number, 
/**
 * Pending checklist for the last successfully completed job.
 */
postflight: PostflightNotice | null, 
/**
 * Alarm recording health; historical rows load only when requested.
 */
alarm_history: HistoryStatus, 
/**
 * Active host process overrides.
 */
soft: SoftView, 
/**
 * Changes with every publication.
 */
revision: number, 
/**
 * The controller task's state.
 */
machine: State, 
/**
 * Whether head calibration applies to the current material.
 */
calibration: CalibrationView, 
/**
 * The operating mode the host is set to.
 */
mode: LaserMode | null, 
/**
 * The machine files, once bound.
 */
bindings: BindingsView | null, 
/**
 * Why the machine files could not be bound.
 */
bindings_error: string | null, 
/**
 * The machine files.
 */
files: FilesView, 
/**
 * The library.
 */
library: LibraryView, 
/**
 * The job being set up.
 */
draft: DraftView | null, 
/**
 * Changes even when the draft is cleared.
 */
draft_revision: number, 
/**
 * The immutable view of the last admitted program.
 */
execution: ExecutionView | null, 
/**
 * Progress interpreted against that program's pass identities.
 */
progress: ProgressView | null, 
/**
 * Whether a held program can be resumed.
 */
can_resume: boolean, 
/**
 * Which commands the server would accept now, and why not otherwise.
 */
readiness: Readiness, 
/**
 * The last thing worth telling the operator.
 */
message: Message | null, 
/**
 * The computer's side of the machine link.
 */
link: LinkView, };
