// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Anchor } from "./Anchor";
import type { Compiled } from "./Compiled";
import type { FeatureSource } from "./FeatureSource";
import type { Features } from "./Features";
import type { Id } from "./Id";
import type { JobPreflight } from "./JobPreflight";
import type { Nesting } from "./Nesting";
import type { Placed } from "./Placed";
import type { PlacementView } from "./PlacementView";
import type { Preview } from "./Preview";
import type { Profile } from "./Profile";
import type { RecipeView } from "./RecipeView";
import type { SheetNavigation } from "./SheetNavigation";

/**
 * The job being set up.
 */
export type DraftView = { 
/**
 * Working-copy identity, distinct from the source part.
 */
key: string, 
/**
 * Selected run type, including while its preview is rebuilding.
 */
dry_run: boolean, 
/**
 * Saved positioning method and the current run's placement state.
 */
placement: PlacementView, 
/**
 * Numbered sheets available without duplicating their canvas paths.
 */
sheets: SheetNavigation | null, 
/**
 * Frozen matrix correction, if applied to this job.
 */
correction: Profile | null, 
/**
 * Nominal, uncorrected calibration coupons.
 */
calibration: boolean, 
/**
 * Stock reference polyline, excluded from cutting and hit selection.
 */
stock_outline: Array<[number, number]>, 
/**
 * Previously removed material in the stock.
 */
stock_cutouts: Array<Array<[number, number]>>, 
/**
 * Stock reference and the last applied nesting settings.
 */
nesting: Nesting | null, 
/**
 * Operator checklist policy.
 */
preflight: JobPreflight, 
/**
 * Identifies this opening of a part or saved job, across its edits.
 */
generation: number, 
/**
 * Identity required when editing or picking geometry.
 */
revision: number, 
/**
 * The part.
 */
part: Id, 
/**
 * The saved job it was opened from, if any.
 */
job: Id | null, 
/**
 * The recipe, once chosen.
 */
recipe: RecipeView | null, 
/**
 * The film process the recipe refers to, as snapshotted with it.
 */
film: RecipeView | null, 
/**
 * The machining features.
 */
features: Features, 
/**
 * Where they came from.
 */
feature_source: FeatureSource | null, 
/**
 * The drawing's contours on the sheet, copies and all.
 */
placed: Array<Placed>, 
/**
 * The contours that move together: an outline with what it encloses,
 * joined across bridges.
 */
groups: Array<Array<number>>, 
/**
 * The origin in machine coordinates: where the anchor point lies,
 * once the part is prepared.
 */
origin: [number, number] | null, 
/**
 * What the machine adds to a drawing coordinate, once the sheet is
 * placed.
 */
zero: [number, number] | null, 
/**
 * Which point of the placed part the origin stands for.
 */
anchor: Anchor, 
/**
 * The anchor point in drawing coordinates, once prepared.
 */
dock: [number, number] | null, 
/**
 * How many edits can be undone.
 */
past: number, 
/**
 * How many undone edits can be redone.
 */
future: number, 
/**
 * The prepared toolpath, for the canvas.
 */
preview: Preview | null, 
/**
 * The compiled program, once compiled.
 */
compiled: Compiled | null, 
/**
 * Why preparation or compilation failed.
 */
error: string | null, };
