// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Id } from "./Id";

/**
 * One part of the job being set up and its contours in the job's drawing.
 */
export type DraftPart = { 
/**
 * The library part.
 */
id: Id, 
/**
 * Its first contour: placed contours with sources from `first` to
 * `first + contours` are this part's.
 */
first: number, 
/**
 * How many contours its drawing has.
 */
contours: number, };
