// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecipeView } from "./RecipeView";

/**
 * One layer of the job.
 */
export type DraftLayer = {
/**
 * Its name.
 */
name: string,
/**
 * Shapes on it, every copy counted.
 */
contours: number,
/**
 * Left uncut.
 */
ignored: boolean,
/**
 * The operator chose how it is cut: a recipe, or ignored.
 */
chosen: boolean,
/**
 * Its own recipe; a chosen layer without one uses the job's.
 */
recipe: RecipeView | null,
/**
 * Engraved on the surface, ahead of the cuts.
 */
engrave: boolean, };
