// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LayerMode } from "./LayerMode";
import type { Machining } from "./Machining";
import type { RecipeView } from "./RecipeView";

/**
 * One layer of the job, in the order the layers run.
 */
export type DraftLayer = {
/**
 * Its name.
 */
name: string,
/**
 * Shapes on it, every copy counted.
 */
contours: number,
/**
 * Whether it is cut at all.
 */
output: boolean,
/**
 * The operator chose how it runs: a recipe, or output off.
 */
chosen: boolean,
/**
 * Its own recipe; a chosen layer without one uses the job's.
 */
recipe: RecipeView | null,
/**
 * Cut through, or marked on the surface.
 */
mode: LayerMode,
/**
 * Its colour: the operator's, else the file's; none takes the
 * screen's cut colour or the next of its palette.
 */
color: [number, number, number] | null,
/**
 * Its own machining, over the job's.
 */
machining: Machining | null, };
