// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Id } from "./Id";

/**
 * One saved library edit.
 */
export type Edit = {
/**
 * Stable edit identity.
 */
id: Id,
/**
 * What changed.
 */
label: string,
/**
 * Time in seconds since the epoch.
 */
at: number, };
