// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Edit } from "./Edit";

/**
 * Saved changes that can be undone or redone, oldest first.
 */
export type EditHistory = { 
/**
 * Changes on every edit, undo and redo.
 */
revision: number, 
/**
 * Applied edits, latest last.
 */
past: Array<Edit>, 
/**
 * Undone edits, next redo last.
 */
future: Array<Edit>, };
