// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One value changed independently in both the draft and the saved job.
 */
export type EditConflict = { 
/**
 * JSON pointer identifying the conflicting value.
 */
path: string, 
/**
 * Value before either edit.
 */
base: string, 
/**
 * Draft value for review.
 */
draft: string, 
/**
 * Saved value for review.
 */
saved: string, };
