// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Compiled } from "./Compiled";
import type { MaterialView } from "./MaterialView";

/**
 * The view belongs to the admitted operation, even if the draft changes.
 */
export type ExecutionView = {
/**
 * Admission identity.
 */
id: number,
/**
 * Whether this is a frame, whose motion never turns on the laser.
 */
frame: boolean,
/**
 * The part or saved job being executed.
 */
name: string,
/**
 * The material snapshot used by this program.
 */
material: MaterialView | null,
/**
 * The selected job anchor in machine coordinates at admission.
 */
origin: [number, number],
/**
 * The sheet offset captured at admission: what the machine adds to a
 * drawing coordinate. Sent as `zero`.
 */
zero: [number, number],
/**
 * The cut job's preview and pass identities. Framing keeps this same
 * geometry visible while its separate laser-off motion runs.
 */
compiled: Compiled, };
