// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Id } from "./Id";

/**
 * Where the features of a draft came from.
 */
export type FeatureSource = { 
/**
 * The job they were copied from.
 */
job: Id, 
/**
 * Its name.
 */
name: string, 
/**
 * When that job was saved.
 */
at: number, };
