// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Bridges } from "./Bridges";
import type { CommonEdges } from "./CommonEdges";
import type { Cooling } from "./Cooling";
import type { CutOrder } from "./CutOrder";
import type { Joints } from "./Joints";
import type { Kerf } from "./Kerf";
import type { Leads } from "./Leads";
import type { Seam } from "./Seam";
import type { Start } from "./Start";

/**
 * Everything preparation needs beyond the drawing.
 */
export type Features = {
/**
 * Entry and exit leads.
 */
leads: Leads | null,
/**
 * Micro-joints that hold parts in the sheet.
 */
joints: Joints | null,
/**
 * Cooling stops.
 */
cooling: Cooling | null,
/**
 * Kerf compensation.
 */
kerf: Kerf | null,
/**
 * Bridges between contours.
 */
bridges: Bridges | null,
/**
 * Share compatible coincident spans between these placed contours.
 */
common: CommonEdges | null,
/**
 * Where each contour starts and which way it runs.
 */
start: Start,
/**
 * How a closed contour's seam is treated.
 */
seam: Seam,
/**
 * The cutting order.
 */
order: CutOrder,
/**
 * Drawing layers left uncut.
 */
skip_layers: Array<string>, };
