// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The FIFO as last read.
 */
export type FifoView = {
/**
 * Free space in bytes.
 */
free: number,
/**
 * Total capacity in bytes, once read.
 */
capacity: number | null,
/**
 * The activity byte: 1 while a program runs.
 */
activity: number,
/**
 * The stamp of the last accepted upload.
 */
stamp: number,
/**
 * The running item tag and progress within it.
 */
item: number,
/**
 * Progress within the running item.
 */
progress: number, };
