// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One machine file.
 */
export type FileView = {
/**
 * The file name.
 */
name: string,
/**
 * Its size.
 */
bytes: number,
/**
 * Its hash.
 */
sha256: string, };
