// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Liters } from "./Liters";

/**
 * What the model expects over a flow test.
 */
export type FlowEstimate = {
/**
 * Uncalibrated.
 */
estimated: Liters,
/**
 * With the gas's current calibration.
 */
calibrated: Liters, };
