// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LitersPerMinute } from "./LitersPerMinute";

/**
 * How the flow of a gas is known.
 */
export type Flow = { "kind": "estimated" } | { "kind": "manual", 
/**
 * The flow.
 */
rate: LitersPerMinute, };
