// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Id } from "./Id";

/**
 * A folder in the parts library.
 */
export type Folder = { 
/**
 * Its id.
 */
id: Id, 
/**
 * Its name.
 */
name: string, 
/**
 * The folder it sits in, or the root.
 */
parent: Id | null, 
/**
 * Whether it is starred.
 */
favourite: boolean, };
