// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Supply } from "./Supply";

/**
 * Settings → Gas costs: the currency and every gas's supply.
 */
export type GasCosts = {
/**
 * The currency symbol money is shown with.
 */
currency: string,
/**
 * Nitrogen.
 */
nitrogen: Supply,
/**
 * Oxygen.
 */
oxygen: Supply,
/**
 * Air.
 */
air: Supply, };
