// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An assist gas, whatever valve or pressure route carries it.
 */
export type GasKind = "nitrogen" | "oxygen" | "air";
