// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Bar } from "./Bar";
import type { GasKind } from "./GasKind";
import type { Liters } from "./Liters";
import type { LitersPerMinute } from "./LitersPerMinute";
import type { Money } from "./Money";
import type { Seconds } from "./Seconds";

/**
 * One gas's share of a job or run.
 */
export type GasLine = { 
/**
 * Which gas.
 */
gas: GasKind, 
/**
 * Its gauge pressure.
 */
pressure: Bar, 
/**
 * Valve-open time.
 */
seconds: Seconds, 
/**
 * The flow used, when known.
 */
flow: LitersPerMinute | null, 
/**
 * The volume, when the flow is known.
 */
litres: Liters | null, 
/**
 * The cost, when priced.
 */
cost: Money | null, };
