// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One gas selection of the machine.
 */
export type GasRouteView = {
/**
 * The selector, 0 to 5.
 */
selector: number,
/**
 * Its name.
 */
name: string,
/**
 * Whether a valve is wired to it.
 */
valve: boolean,
/**
 * Whether its pressure is set electronically, through a proportional
 * output; otherwise it is set at the regulator.
 */
pressure: boolean, };
