// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Bar } from "./Bar";
import type { GasKind } from "./GasKind";
import type { Seconds } from "./Seconds";

/**
 * Time one gas flowed at one pressure.
 */
export type GasTime = {
/**
 * Which gas.
 */
gas: GasKind,
/**
 * The regulated gauge pressure it flowed at.
 */
pressure: Bar,
/**
 * How long its valve was open.
 */
seconds: Seconds, };
