// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Consumption } from "./Consumption";
import type { GasCosts } from "./GasCosts";
import type { SupplyView } from "./SupplyView";

/**
 * Gas costs as every screen sees them.
 */
export type GasView = { 
/**
 * Changes when prices or recorded runs change.
 */
revision: number, 
/**
 * The saved settings.
 */
costs: GasCosts, 
/**
 * Derived prices, in [`GasKind::ALL`] order.
 */
supplies: Array<SupplyView>, 
/**
 * One run of the job being set up, once it is compiled.
 */
estimate: Consumption | null, 
/**
 * Why saved prices or runs could not be read or written.
 */
error: string | null, };
