// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether one command would be accepted.
 */
export type Gate = { 
/**
 * Whether it would.
 */
ok: boolean, 
/**
 * Why not, when not.
 */
reason: string | null, };
