// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The head controller as last read.
 */
export type HeadView = { 
/**
 * Whether the head holds a reference.
 */
referenced: boolean, 
/**
 * The head height in millimetres.
 */
height_mm: number, 
/**
 * The command in progress, zero when idle.
 */
command: number, 
/**
 * The head status byte.
 */
status: number, };
