// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Recording health and the revision used to refresh an open history panel.
 */
export type HistoryStatus = {
/**
 * Changes after every recorded transition or reset result.
 */
revision: number,
/**
 * A storage failure; never silently represented as successful recording.
 */
error: string | null, };
