// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AlarmSession } from "./AlarmSession";

/**
 * A page of restart groups, newest first.
 */
export type HistoryPage = { 
/**
 * Current application session, for labelling rather than live alarm state.
 */
current: string, 
/**
 * Up to ten restart groups.
 */
sessions: Array<AlarmSession>, 
/**
 * Cursor for older groups, if more remain.
 */
before: string | null, };
