// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Hold durations in milliseconds.
 */
export type HoldTimes = { 
/**
 * Moving the machine, firing the beam or switching an output on.
 */
move_ms: number, 
/**
 * Setting an origin or a reference.
 */
zero_ms: number, };
