// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A time-ordered item id. A process-local clock keeps IDs distinct when the
 * system clock repeats a tick or moves backwards.
 */
export type Id = string;
