// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The controller's identity.
 */
export type Identity = {
/**
 * The product id; 103 for the MCC100.
 */
product_id: number,
/**
 * The program version; 20177 for firmware 201.77.
 */
program_version: number, };
