// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Bounds } from "./Bounds";
import type { ImportLayer } from "./ImportLayer";
import type { Repairs } from "./Repairs";
import type { ScaleReview } from "./ScaleReview";
import type { SizeCheck } from "./SizeCheck";

/**
 * What importing a file would make, for review before it is kept.
 */
export type ImportReview = {
/**
 * The file's name.
 */
name: string,
/**
 * The layers with geometry, and which are imported.
 */
layers: Array<ImportLayer>,
/**
 * How an SVG's size was read; absent for DXF.
 */
scale: ScaleReview | null,
/**
 * What import repaired, and where.
 */
repairs: Repairs,
/**
 * Whether the size is plausible; absent when nothing is imported.
 */
size: SizeCheck | null,
/**
 * The extent of the imported geometry.
 */
bounds: Bounds | null,
/**
 * How many contours would be imported.
 */
contours: number,
/**
 * The contours that are open.
 */
open: Array<number>,
/**
 * The closed contours that cross themselves.
 */
crossing: Array<number>,
/**
 * Every contour as a polyline, for the preview.
 */
outline: Array<Array<[number, number]>>,
/**
 * Notices to read before keeping the part.
 */
warnings: Array<string>, };
