// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A layer of the file that holds geometry.
 */
export type ImportLayer = {
/**
 * The name, as the file writes it.
 */
name: string,
/**
 * Whether the file turns it off or freezes it.
 */
hidden: boolean,
/**
 * Whether its geometry is imported.
 */
imported: boolean,
/**
 * How many entities it holds.
 */
entities: number, };
