// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A physical contour instance before feature preparation.
 */
export type InstanceView = { 
/**
 * The contour in the source drawing.
 */
source: number, 
/**
 * The placed copy of that drawing.
 */
copy: number, };
