// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Id } from "./Id";

/**
 * A rename, a move to a folder, or a star.
 */
export type ItemChange = {
/**
 * Operator tags.
 */
tags?: Array<string>,
/**
 * Operator notes.
 */
notes?: string,
/**
 * Requested production quantity.
 */
quantity?: number,
/**
 * The new name.
 */
name?: string,
/**
 * The new folder; `Some(None)` moves to the root.
 */
folder?: Id | null,
/**
 * Starred or not.
 */
favourite?: boolean, };
