// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Check } from "./Check";

/**
 * How a saved job chooses its checks. Old jobs inherit the mode defaults.
 */
export type JobPreflight = { "kind": "inherit", } | { "kind": "off", } | { "kind": "custom", 
/**
 * Checks in display order.
 */
steps: Array<Check>, };
