// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Bounds } from "./Bounds";
import type { Id } from "./Id";
import type { RecipeView } from "./RecipeView";
import type { SheetInfo } from "./SheetInfo";

/**
 * A saved job.
 */
export type JobView = { 
/**
 * Membership in a saved sheet set.
 */
sheet: SheetInfo | null, 
/**
 * Extent of the saved placements, including scaling and removed contours.
 */
bounds: Bounds | null, 
/**
 * Thumbnail of the saved placements.
 */
outline: Array<Array<[number, number]>>, 
/**
 * Number of saved placed contours.
 */
contours: number, 
/**
 * Searchable operator tags.
 */
tags: Array<string>, 
/**
 * Operator notes.
 */
notes: string, 
/**
 * Requested production quantity.
 */
quantity: number, 
/**
 * Its id.
 */
id: Id, 
/**
 * Its name.
 */
name: string, 
/**
 * Its folder.
 */
folder: Id | null, 
/**
 * The parts it cuts, in the order of its drawing.
 */
parts: Array<Id>, 
/**
 * The recipe it was saved with.
 */
recipe: RecipeView, 
/**
 * Which features are on.
 */
features_on: Array<string>, 
/**
 * Whether it is starred.
 */
favourite: boolean, 
/**
 * When it last changed.
 */
updated: number, };
