// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A jog request from the UI.
 */
export type JogRequest = {
/**
 * 0 for X, 1 for Y.
 */
axis: number,
/**
 * The direction: positive or negative.
 */
positive: boolean,
/**
 * The step in millimetres, or `None` for a held jog to the limit.
 */
step_mm: number | null,
/**
 * Fast or slow.
 */
fast: boolean,
/**
 * For a diagonal jog, the direction of the other axis. Both axes travel
 * the same distance, so the head moves at 45° and stops at whichever
 * limit comes first.
 */
diagonal?: boolean, };
