// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Millimeters } from "./Millimeters";
import type { Spot } from "./Spot";

/**
 * Where micro-joints go.
 */
export type JointPlacement = { "count": number } | { "spacing": Millimeters } | { "across_x": number } | { "across_y": number } | { "manual": Array<Spot> };
