// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Percent } from "./Percent";

/**
 * What the laser does in a joint.
 */
export type JointBehaviour = "laser_off" | { "power": Percent };
