// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JointBehaviour } from "./JointBehaviour";
import type { JointPlacement } from "./JointPlacement";
import type { Millimeters } from "./Millimeters";
import type { MmPerSecond } from "./MmPerSecond";

/**
 * Micro-joints: short gaps in the cut that hold a part in the sheet.
 */
export type Joints = { 
/**
 * Where the joints go.
 */
placement: JointPlacement, 
/**
 * How wide each joint is along the contour.
 */
width: Millimeters, 
/**
 * Contours smaller than this in both directions get no joints.
 */
minimum_size: Millimeters, 
/**
 * Joint only outlines, never holes.
 */
outer_only: boolean, 
/**
 * On an open contour, put a joint at its start as well.
 */
open_start: boolean, 
/**
 * How the laser behaves in a joint.
 */
behaviour: JointBehaviour, 
/**
 * A slower speed through the joint.
 */
slow_speed: MmPerSecond | null, 
/**
 * Pierce again after each joint.
 */
repierce: boolean, };
