// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Millimeters } from "./Millimeters";
import type { Side } from "./Side";

/**
 * Kerf compensation: the path moves half the kerf into the waste.
 */
export type Kerf = {
/**
 * The width the beam removes.
 */
width: Millimeters,
/**
 * Which side the waste is on.
 */
side: Side, };
