// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which laser the machine is set up to fire. The M-series carries both and
 * the operator selects one; the choice changes head behaviour, outputs and
 * the process fields in every record.
 */
export type LaserMode = "fiber" | "co2";
