// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LayerMode } from "./LayerMode";
import type { Machining } from "./Machining";

/**
 * One of the job's layers.
 */
export type Layer = {
/**
 * Its name.
 */
name: string,
/**
 * What it does to the sheet.
 */
mode: LayerMode,
/**
 * Its colour on screen, over the drawing's own.
 */
color: [number, number, number] | null,
/**
 * Its own machining, over the job's.
 */
machining: Machining | null, };
