// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One shape on a layer of the operator's choosing. The shape is a contour
 * of the job's drawing, so every copy of it follows.
 */
export type LayerEdit = {
/**
 * The drawing contour.
 */
contour: number,
/**
 * The layer it is on.
 */
layer: string, };
