// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Id } from "./Id";

/**
 * A change to the job's layers; each is one undo step.
 */
export type LayerChange = { "kind": "assign",
/**
 * Placed contours; every copy of each shape moves with it.
 */
contours: Array<number>,
/**
 * The layer they go to.
 */
layer: string, } | { "kind": "rename",
/**
 * Its name now.
 */
from: string,
/**
 * Its new name.
 */
to: string, } | { "kind": "cut",
/**
 * The layer.
 */
layer: string,
/**
 * A library recipe; none uses the job's.
 */
recipe: Id | null,
/**
 * Engraved on the surface instead of cut through.
 */
engrave: boolean, } | { "kind": "ignore",
/**
 * The layer.
 */
layer: string, };
