// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One drawing layer.
 */
export type LayerView = { 
/**
 * Its name in the drawing.
 */
name: string, 
/**
 * How many contours lie on it.
 */
contours: number, };
