// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Id } from "./Id";
import type { LayerMode } from "./LayerMode";

/**
 * A change to the job's layers; each is one undo step.
 */
export type LayerChange = { "kind": "assign",
/**
 * Placed contours; every copy of each shape moves with it.
 */
contours: Array<number>,
/**
 * The layer they go to.
 */
layer: string, } | { "kind": "rename",
/**
 * Its name now.
 */
from: string,
/**
 * Its new name.
 */
to: string, } | { "kind": "recipe",
/**
 * The layer.
 */
layer: string,
/**
 * A library recipe; none uses the job's.
 */
recipe: Id | null, } | { "kind": "output",
/**
 * The layer.
 */
layer: string,
/**
 * Whether it is cut.
 */
on: boolean, } | { "kind": "mode",
/**
 * The layer.
 */
layer: string,
/**
 * What it does.
 */
mode: LayerMode, } | { "kind": "color",
/**
 * The layer.
 */
layer: string,
/**
 * Red, green and blue.
 */
color: [number, number, number] | null, } | { "kind": "order",
/**
 * Every layer, first to last.
 */
layers: Array<string>, };
