// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Lead } from "./Lead";
import type { LeadOverride } from "./LeadOverride";
import type { Side } from "./Side";

/**
 * Entry and exit leads.
 */
export type Leads = {
/**
 * The lead-in, if any.
 */
entry: Lead | null,
/**
 * The lead-out, if any.
 */
exit: Lead | null,
/**
 * Which side of the contour the leads lie on.
 */
side: Side,
/**
 * Leave open contours without leads.
 */
closed_only: boolean,
/**
 * Leads edited on the drawing. Locations name placed contours and
 * distinguish pieces created by a bridge split.
 */
overrides: Array<LeadOverride>, };
