// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Lead } from "./Lead";
import type { Spot } from "./Spot";

/**
 * A lead edit anchored to one placed contour. The retained location follows
 * that contour through moves, copies and bridge operations; it does not
 * change the cutting start. A missing role inherits its job default.
 */
export type LeadOverride = { 
/**
 * A retained point on the owning source contour, before compensation.
 */
location: Spot, 
/**
 * The local entry definition, if edited.
 */
entry: Lead | null, 
/**
 * The local exit definition, if edited.
 */
exit: Lead | null, };
