// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Degrees } from "./Degrees";
import type { LeadShape } from "./LeadShape";
import type { Millimeters } from "./Millimeters";

/**
 * One lead.
 */
export type Lead = { 
/**
 * Its shape.
 */
shape: LeadShape, 
/**
 * The length of the straight part.
 */
length: Millimeters, 
/**
 * The radius of the arc part.
 */
radius: Millimeters, 
/**
 * The angle between the lead and the contour, or the arc's sweep.
 */
angle: Degrees, };
