// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A browser instance and its monotonically increasing press number.
 */
export type Lease = {
/**
 * Random instance id, changed when the page is reloaded.
 */
client: string,
/**
 * Increased for each press within that instance.
 */
sequence: number, };
