// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Folder } from "./Folder";
import type { JobView } from "./JobView";
import type { PartView } from "./PartView";
import type { RecipeView } from "./RecipeView";
import type { SkippedView } from "./SkippedView";

/**
 * The library, summarised.
 */
export type LibraryView = {
/**
 * Every folder.
 */
folders: Array<Folder>,
/**
 * Every part.
 */
parts: Array<PartView>,
/**
 * Every recipe.
 */
recipes: Array<RecipeView>,
/**
 * Every job.
 */
jobs: Array<JobView>,
/**
 * Library files left out when it opened, untouched on disk.
 */
skipped: Array<SkippedView>, };
