// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Folder } from "./Folder";
import type { JobView } from "./JobView";
import type { PartView } from "./PartView";
import type { RecipeView } from "./RecipeView";
import type { SheetView } from "./SheetView";
import type { SkippedView } from "./SkippedView";
import type { StockItem } from "./StockItem";

/**
 * The library, summarised.
 */
export type LibraryView = {
/**
 * Every folder.
 */
folders: Array<Folder>,
/**
 * Every part.
 */
parts: Array<PartView>,
/**
 * Every recipe.
 */
recipes: Array<RecipeView>,
/**
 * Every job.
 */
jobs: Array<JobView>,
/**
 * Full sheets on the rack.
 */
stock: Array<StockItem>,
/**
 * Remnants ready to nest on.
 */
remnants: Array<SheetView>,
/**
 * Library files left out when it opened, untouched on disk.
 */
skipped: Array<SkippedView>, };
