// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A step of the connect workflow.
 */
export type LinkPhase = "idle" | "inspecting" | "configuring" | "connecting" | "reading" | "failed";
