// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A gas volume at standard conditions (20 °C, 1 atm).
 */
export type Liters = number;
