// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Cooling } from "./Cooling";
import type { Joints } from "./Joints";
import type { Kerf } from "./Kerf";
import type { Leads } from "./Leads";
import type { Seam } from "./Seam";
import type { Start } from "./Start";

/**
 * What happens along a layer's contours, when the layer has its own.
 * Picked places, such as manual starts, joints and lead edits, stay the
 * job's, so a layer's manual joints are the job's manual joints.
 */
export type Machining = {
/**
 * Entry and exit leads.
 */
leads: Leads | null,
/**
 * Micro-joints.
 */
joints: Joints | null,
/**
 * Cooling stops.
 */
cooling: Cooling | null,
/**
 * Kerf compensation.
 */
kerf: Kerf | null,
/**
 * Where each contour starts and which way it runs.
 */
start: Start,
/**
 * How a closed contour's seam is treated.
 */
seam: Seam, };
