// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LaserMode } from "./LaserMode";
import type { RecipeSummary } from "./RecipeSummary";

/**
 * The material identity shown beside an immutable execution.
 */
export type MaterialView = {
/**
 * The material name.
 */
name: string,
/**
 * Sheet thickness in millimetres.
 */
thickness_mm: number,
/**
 * The assist gas.
 */
gas: string,
/**
 * The laser this recipe uses.
 */
laser: LaserMode,
/**
 * The recipe's headline values as the program was compiled with them.
 */
summary: RecipeSummary, };
