// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Effective centreline dimensions of one cooled coupon, in millimetres.
 */
export type Measurement = {
/**
 * Width along the machine X axis.
 */
x: number,
/**
 * Height along the machine Y axis.
 */
y: number, };
