// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EditConflict } from "./EditConflict";

/**
 * A merge review bound to both the current working copy and saved job.
 */
export type MergeReview = { 
/**
 * Changes if either input changes.
 */
token: string, 
/**
 * Name after merging the nonconflicting values.
 */
name: string, 
/**
 * Only values requiring an operator choice.
 */
conflicts: Array<EditConflict>, };
