// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A note for the operator, with when it was raised.
 */
export type Message = {
/**
 * Unique publication id, including notes raised within the same second.
 */
id: number,
/**
 * The text.
 */
text: string,
/**
 * Whether it reports a failure.
 */
error: boolean,
/**
 * Seconds since the epoch.
 */
at: number, };
