// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PathKind } from "./PathKind";

/**
 * A sampled motion section of the program.
 */
export type Move = { 
/**
 * What the laser does along it.
 */
kind: PathKind, 
/**
 * The pass, for progress.
 */
pass: number | null, 
/**
 * The polyline.
 */
points: Array<[number, number]>, };
