// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NestSettings } from "./NestSettings";
import type { StockSource } from "./StockSource";

/**
 * Simple operator choices for one search.
 */
export type NestRequest = {
/**
 * Selected contour identities; quantity requires one complete group.
 */
contours: Array<number>,
/**
 * Required copies of the selected part, including the original.
 */
quantity: number,
/**
 * Distances and rotation constraint.
 */
settings: NestSettings,
/**
 * Bounded search duration, between one and thirty seconds.
 */
seconds: number,
/**
 * The sheets to fill, in order; empty uses the draft's stock, then
 * full sheets of its size when it is a remnant.
 */
stock: Array<StockSource>, };
