// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Preview } from "./Preview";

/**
 * Preview geometry for exactly one sheet.
 */
export type NestSheetPreview = { 
/**
 * Prepared cutting geometry.
 */
preview: Preview | null, 
/**
 * Outer reference boundary.
 */
stock_outline: Array<[number, number]>, 
/**
 * Previously removed regions.
 */
stock_cutouts: Array<Array<[number, number]>>, };
