// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A compact summary in a nesting preview's sheet switcher.
 */
export type NestSheetSummary = {
/**
 * One-based sheet number.
 */
number: number,
/**
 * Physical copies on this sheet.
 */
parts: number,
/**
 * Area fraction used on this sheet.
 */
coverage: number,
/**
 * Which of the requested stock sources it is; with none requested, 0
 * is the draft's stock and 1 full sheets after a remnant.
 */
source: number,
/**
 * Outer width and height of the sheet in millimetres.
 */
size: [number, number], };
