// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NestRotation } from "./NestRotation";

/**
 * Minimum distances in millimetres, independent of machining clearance.
 */
export type NestSettings = { 
/**
 * Extra distance from old cutouts and the outer edge for manual remnant alignment.
 */
remnant_clearance: number, 
/**
 * Minimum distance between part edges.
 */
spacing: number, 
/**
 * Minimum distance from stock edges.
 */
margin: number, 
/**
 * Grain/orientation constraint.
 */
rotation: NestRotation, };
