// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Bounds } from "./Bounds";
import type { Contour } from "./Contour";
import type { Placed } from "./Placed";

/**
 * Stock is a reference boundary, never a cutting contour.
 */
export type NestStock = { "kind": "rectangle", 
/**
 * Sheet bounds.
 */
bounds: Bounds, } | { "kind": "remnant", 
/**
 * Library identity for provenance; geometry remains usable independently.
 */
reference: string, 
/**
 * Operator's sheet name.
 */
name: string, 
/**
 * Retained outer boundary in drawing coordinates.
 */
outline: Contour, 
/**
 * Regions from which material has already been removed.
 */
cutouts: Array<Contour>, 
/**
 * Conservative clearance for kerf and leads used by previous cuts.
 */
clearance: number, } | { "kind": "outline", 
/**
 * Its source and placement before it was removed from cutting.
 */
contour: Placed, };
