// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NestCopy } from "./NestCopy";

/**
 * Where a running search has the draft's groups on the sheet it is filling
 * or compacting: each copy clear of the others, not yet checked against the
 * stock's own curves, and never applied.
 */
export type NestLive = { 
/**
 * One-based number of the sheet shown: the one the search last changed.
 */
sheet: number, 
/**
 * The shown sheet's outer boundary.
 */
stock_outline: Array<[number, number]>, 
/**
 * Material already removed from the shown sheet.
 */
stock_cutouts: Array<Array<[number, number]>>, 
/**
 * Every copy on the shown sheet.
 */
copies: Array<NestCopy>, };
