// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A compact summary in a nesting preview's sheet switcher.
 */
export type NestSheetSummary = {
/**
 * One-based sheet number.
 */
number: number,
/**
 * Physical copies on this sheet.
 */
parts: number,
/**
 * Area fraction used on this sheet.
 */
coverage: number,
/**
 * Fresh stock instead of the original remnant.
 */
fresh: boolean, };
