// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Allowed rotations relative to each part's current orientation.
 */
export type NestRotation = "any" | "half_turn" | "across" | "fixed";
