// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NestSettings } from "./NestSettings";
import type { NestStock } from "./NestStock";

/**
 * Nesting authoring data saved with a job and in undo history.
 */
export type Nesting = {
/**
 * The stock outline.
 */
stock: NestStock,
/**
 * Minimum spacing and allowed rotations.
 */
settings: NestSettings, };
