// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Transform } from "./Transform";

/**
 * One copy of one of the draft's groups in a running search.
 */
export type NestCopy = {
/**
 * The group, as the draft lists its groups.
 */
group: number,
/**
 * Moves the group from where it lies now to where the copy goes.
 */
transform: Transform, };
