// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A compact summary in a nesting preview's sheet switcher.
 */
export type NestSheetSummary = {
/**
 * One-based sheet number.
 */
number: number,
/**
 * Physical copies on this sheet.
 */
parts: number,
/**
 * Area fraction used on this sheet.
 */
coverage: number,
/**
 * Which of the requested stock sources it is; 0, the draft's own
 * sheet, when none were requested.
 */
source: number,
/**
 * Outer width and height of the sheet in millimetres.
 */
size: [number, number], };
