// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LaserMode } from "./LaserMode";
import type { Values } from "./Values";

/**
 * A recipe to add.
 */
export type NewRecipe = { 
/**
 * The material.
 */
name: string, 
/**
 * Which laser.
 */
laser: LaserMode, 
/**
 * The sheet thickness.
 */
thickness_mm: number, 
/**
 * Where its values come from.
 */
values: Values, 
/**
 * The gas selection, 0 to 5, when it should differ from the source's.
 */
gas: number | null, };
