// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Id } from "./Id";
import type { LaserMode } from "./LaserMode";

/**
 * Sheets to add: an existing entry of the same material, size and folder
 * gains the quantity, otherwise a new entry starts.
 */
export type NewStock = {
/**
 * Material name, as the recipes name it.
 */
material: string,
/**
 * Thickness in millimetres.
 */
thickness_mm: number,
/**
 * The laser its recipes are for.
 */
laser: LaserMode,
/**
 * Along X, in millimetres.
 */
width_mm: number,
/**
 * Along Y, in millimetres.
 */
height_mm: number,
/**
 * Sheets to add.
 */
quantity: number,
/**
 * The folder to keep them in.
 */
folder: Id | null, };
