// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Millimeters } from "./Millimeters";
import type { NozzleType } from "./NozzleType";

/**
 * The nozzle a recipe fits.
 */
export type Nozzle = { 
/**
 * Exit diameter.
 */
diameter: Millimeters, 
/**
 * Single or double layer.
 */
kind: NozzleType, };
