// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationKind } from "./OperationKind";

/**
 * The active operation.
 */
export type OperationView = { 
/**
 * Its kind.
 */
kind: OperationKind, 
/**
 * Its phase, as a short label.
 */
phase: string, 
/**
 * Seconds since it started.
 */
age_seconds: number, };
