// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What kind of operation is active.
 */
export type OperationKind = "home" | "calibrate" | "motion" | "mode_switch" | "relief" | "outputs" | "program" | "parameters";
