// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A manual output request from the UI.
 */
export type OutputRequest = { "kind": "pointer" } | { "kind": "shutter" } | { "kind": "gas", 
/**
 * The selector, 0 to 5.
 */
selector: number, 
/**
 * The pressure in bar.
 */
pressure: number, } | { "kind": "head_jog", 
/**
 * Up or down.
 */
up: boolean, 
/**
 * Fast or slow.
 */
fast: boolean, };
