// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which manual outputs the machine has.
 */
export type OutputsView = { 
/**
 * A red pointer.
 */
pointer: boolean, 
/**
 * Selected source's red-light output, zero when unassigned.
 */
pointer_port: number, 
/**
 * A shutter or laser gate.
 */
shutter: boolean, 
/**
 * Selected source's gate output, zero when unassigned.
 */
shutter_port: number, 
/**
 * Gas selectors with a valve: low air, oxygen, nitrogen, high air,
 * oxygen, nitrogen.
 */
gas: [boolean, boolean, boolean, boolean, boolean, boolean], 
/**
 * A head that can be jogged.
 */
head_jog: boolean, };
