// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Bounds } from "./Bounds";
import type { Id } from "./Id";
import type { LayerView } from "./LayerView";

/**
 * A part without its geometry.
 */
export type PartView = { 
/**
 * Searchable operator tags.
 */
tags: Array<string>, 
/**
 * Operator notes.
 */
notes: string, 
/**
 * Requested production quantity.
 */
quantity: number, 
/**
 * Its id.
 */
id: Id, 
/**
 * Its name.
 */
name: string, 
/**
 * Its folder.
 */
folder: Id | null, 
/**
 * The file it came from.
 */
file_name: string, 
/**
 * Its extent.
 */
bounds: Bounds | null, 
/**
 * How many contours it has.
 */
contours: number, 
/**
 * A thumbnail: the contours as polylines in drawing coordinates.
 */
outline: Array<Array<[number, number]>>, 
/**
 * The drawing's layers and how many contours each holds.
 */
layers: Array<LayerView>, 
/**
 * Whether it is starred.
 */
favourite: boolean, 
/**
 * When it last changed.
 */
updated: number, };
