// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The processes counted separately by execution progress.
 */
export type PassKind = "pre_pierce" | "film" | "cut";
