// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstanceView } from "./InstanceView";
import type { PassKind } from "./PassKind";

/**
 * One process in the admitted pass plan.
 */
export type PassView = { 
/**
 * Its ordinal in the original job, preserved through continuation.
 */
ordinal: number, 
/**
 * What the process does.
 */
kind: PassKind, 
/**
 * The physical instances from which this prepared path was made.
 */
instances: Array<InstanceView>, 
/**
 * Requested cooling points omitted by the native endpoint tolerance.
 */
omitted_cooling: number, };
