// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PathKind } from "./PathKind";

/**
 * A polyline and the process it is cut with.
 */
export type Path = { 
/**
 * What the laser does along it.
 */
kind: PathKind, 
/**
 * The polyline in drawing coordinates.
 */
points: Array<[number, number]>, };
