// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a path does, for the canvas layers.
 */
export type PathKind = "travel" | "cut" | "film" | "lead_in" | "lead_out" | "joint" | "cooling" | "cleaning";
