// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Checklist } from "./Checklist";

/**
 * Editable pause checks for each laser mode.
 */
export type PauseDefaults = { 
/**
 * Fiber pause checks.
 */
fiber: Checklist, 
/**
 * CO2 pause checks.
 */
co2: Checklist, };
