// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Id } from "./Id";

/**
 * One retained draft in the pending-edits review.
 */
export type PendingDraft = { 
/**
 * Retained draft identity, independent of the active page.
 */
key: string, 
/**
 * Name of the saved job or source part.
 */
name: string, 
/**
 * Source part.
 */
part: Id, 
/**
 * Saved job, if there is one.
 */
job: Id | null, 
/**
 * Whether it has a material and can be saved as a job.
 */
can_save: boolean, 
/**
 * Missing or invalid source that prevents opening this retained draft.
 */
problem: string | null, };
