// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Spot } from "./Spot";

/**
 * A tap on the drawing snapped to a contour.
 */
export type PickView = { 
/**
 * The contour and the fraction along it, as the features refer to it.
 */
spot: Spot, 
/**
 * The point on the contour, in drawing coordinates.
 */
point: [number, number], 
/**
 * The placed contour whose local coordinates hold `point`.
 */
owner: number, };
