// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Point } from "./Point";

/**
 * A point picked on a contour.
 */
export type Pick = {
/**
 * The contour, as an index into the contours at the time of the pick.
 */
contour: number,
/**
 * Point in the local coordinates of the result's lowest original
 * placed owner; preparation resolves that owner through prior bridges.
 */
point: Point, };
