// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a new physical sheet is positioned on the machine.
 */
export type Placement = { "kind": "head", } | { "kind": "fixed", 
/**
 * Machine XY occupied by the sheet's reference point, in millimetres.
 */
origin: [number, number], };
