// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Explicit changes made in the Run positioning panel. None causes motion.
 */
export type PlacementChange = { "kind": "head", } | { "kind": "set_origin", } | { "kind": "fixed_head", } | { "kind": "fixed",
/**
 * Machine millimetres from the homed zero.
 */
origin: [number, number], } | { "kind": "reposition", } | { "kind": "new_run", };
