// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlacementMode } from "./PlacementMode";

/**
 * Per-run captures are transient; absolute fixture coordinates belong to the job.
 */
export type PlacementView = { 
/**
 * Positioning method.
 */
mode: PlacementMode, 
/**
 * A fixed fixture, or a head location captured and not yet used by a
 * real run, is available. An each-run origin a run has used is replaced
 * at the next run's start, so it no longer counts as set.
 */
captured: boolean, 
/**
 * Correction awaits a physical location; the current preview is nominal.
 */
correction_pending: boolean, 
/**
 * The method and fixture values match the saved job.
 */
saved: boolean, };
