// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlacementMode } from "./PlacementMode";

/**
 * Per-run captures are transient; absolute fixture coordinates belong to the job.
 */
export type PlacementView = { 
/**
 * Positioning method.
 */
mode: PlacementMode, 
/**
 * A fixed fixture or captured head location is available.
 */
captured: boolean, 
/**
 * Correction awaits a physical location; the current preview is nominal.
 */
correction_pending: boolean, 
/**
 * The method and fixture values match the saved job.
 */
saved: boolean, };
