// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Transform } from "./Transform";

/**
 * A contour of a drawing on the sheet: which one, which copy of the
 * drawing it belongs to, and where it lies.
 */
export type Placed = {
/**
 * The drawing contour.
 */
source: number,
/**
 * Which copy of the drawing; the drawing itself is 0.
 */
copy: number,
/**
 * Where it lies.
 */
transform: Transform, };
