// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A point, or a displacement, in millimetres.
 */
export type Point = { 
/**
 * The X coordinate.
 */
x: number, 
/**
 * The Y coordinate.
 */
y: number, };
