// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Check } from "./Check";
import type { PostflightNotice } from "./PostflightNotice";

/**
 * Current completion checks. Checkbox state is never persisted.
 */
export type PostflightReview = { 
/**
 * Completion identity.
 */
notice: PostflightNotice, 
/**
 * Defaults captured when the job finished.
 */
steps: Array<Check>, 
/**
 * Checks satisfied by fresh machine feedback.
 */
satisfied: Array<number>, };
