// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A pending completion, included in the event stream for every open client.
 */
export type PostflightNotice = { 
/**
 * Unique to this completion and server session.
 */
id: string, 
/**
 * Name of the job that completed.
 */
name: string, };
