// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Checklist } from "./Checklist";

/**
 * Mode-specific checklists offered after a completed or stopped job.
 */
export type PostflightDefaults = { 
/**
 * Fiber completion checks.
 */
fiber: Checklist, 
/**
 * CO2 completion checks.
 */
co2: Checklist, };
