// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Check } from "./Check";
import type { PreflightIntent } from "./PreflightIntent";

/**
 * The exact checks displayed before an operation.
 */
export type PreflightReview = { 
/**
 * Freshness token, invalid after relevant changes or application restart.
 */
token: string, 
/**
 * What the confirmation admits.
 */
intent: PreflightIntent, 
/**
 * Checks in order; indexes are their IDs within this review.
 */
steps: Array<Check>, 
/**
 * Opted-in checks satisfied by current, fresh machine or job state.
 */
satisfied: Array<number>, 
/**
 * Required gases from the compiled cutting, piercing, residue and film passes.
 */
gases: Array<string>, 
/**
 * Whether a gas-readiness checkbox is required.
 */
confirm_gas: boolean, 
/**
 * Whether the compiled program has its laser off.
 */
dry_run: boolean, };
