// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Checklist } from "./Checklist";
import type { PauseDefaults } from "./PauseDefaults";
import type { PostflightDefaults } from "./PostflightDefaults";

/**
 * Application-wide preflight choices, persisted independently of job files.
 */
export type PreflightPreferences = { 
/**
 * File schema version.
 */
version: number, 
/**
 * Optimistic concurrency token for preference edits.
 */
revision: number, 
/**
 * Fiber defaults.
 */
fiber: Checklist, 
/**
 * CO2 defaults.
 */
co2: Checklist, 
/**
 * Legacy version-1 setting, migrated into editable checklist steps.
 */
confirm_gas: boolean, 
/**
 * Checklists offered after confirmed job completion.
 */
postflight: PostflightDefaults, 
/**
 * Checks offered after pausing and required before resuming.
 */
pause: PauseDefaults, };
