// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A fresh operator response. Never persisted or reused for a later run.
 */
export type PreflightConfirmation = {
/**
 * Token from the review shown to the operator.
 */
token: string,
/**
 * Index of each checked step.
 */
checked: Array<number>,
/**
 * Operator confirmation of the displayed gas supplies.
 */
gas_ready: boolean, };
