// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The operation the operator is reviewing.
 */
export type PreflightIntent = "run" | "resume";
