// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Bounds } from "./Bounds";
import type { PreviewContour } from "./PreviewContour";

/**
 * The prepared toolpath as polylines.
 */
export type Preview = { 
/**
 * The contours in cutting order, as polylines in drawing coordinates.
 */
contours: Array<PreviewContour>, 
/**
 * The extent of the placed part.
 */
bounds: Bounds | null, 
/**
 * Total cut length in millimetres.
 */
length_mm: number, 
/**
 * Preparation warnings.
 */
warnings: Array<string>, };
