// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Path } from "./Path";
import type { Spot } from "./Spot";

/**
 * One prepared contour.
 */
export type PreviewContour = { 
/**
 * Stable placed-source location for this contour's lead edits.
 */
lead_target: Spot | null, 
/**
 * Corresponding contour in repeated parts, before placement transforms.
 */
matching_contour: number | null, 
/**
 * Whether it is closed.
 */
closed: boolean, 
/**
 * The nesting depth: zero for an outer contour.
 */
depth: number, 
/**
 * The drawing layer it came from.
 */
layer: string, 
/**
 * The drawing contours it was made from.
 */
sources: Array<number>, 
/**
 * The path in cutting order, split where the process changes.
 */
paths: Array<Path>, 
/**
 * Where the cooling stops are.
 */
cooling: Array<[number, number]>, 
/**
 * The start of the cut, after the lead-in.
 */
start: [number, number], };
