// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Bounds } from "./Bounds";
import type { Measurement } from "./Measurement";

/**
 * A reproducible measurement set in machine coordinates.
 */
export type Profile = { 
/**
 * Bed bounds used to place the measured squares.
 */
bed: Bounds, 
/**
 * Bottom row first, left to right, then middle and top rows.
 */
measurements: [Measurement, Measurement, Measurement, Measurement, Measurement, Measurement, Measurement, Measurement, Measurement], };
