// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Item-tag progress; the unverified native progress unit is not used.
 */
export type ProgressView = {
/**
 * Confirmed completed passes in this execution.
 */
completed: number,
/**
 * The pass being approached or processed, when the tag names one.
 */
pass: number | null,
/**
 * Whether its approach is active; for preliminary points the tag also
 * covers the point process until its completion checkpoint.
 */
approaching: boolean, };
