// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CheckpointView } from "./CheckpointView";
import type { ProgramState } from "./ProgramState";

/**
 * The last program.
 */
export type ProgramView = { 
/**
 * Where it stands.
 */
state: ProgramState, 
/**
 * Whether feedback was captured after FIFO start was acknowledged.
 */
started: boolean, 
/**
 * Blocks acknowledged by the controller.
 */
uploaded: number, 
/**
 * Blocks in the program.
 */
total: number, 
/**
 * The execution checkpoint captured at the pause or stop.
 */
checkpoint: CheckpointView | null, 
/**
 * Why it stopped early, if it did.
 */
error: string | null, };
