// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The quality the head controller reports after a calibration.
 */
export type Quality = "excellent" | "good" | "bad";
