// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Gate } from "./Gate";

/**
 * The gates the UI enables its controls from. The server checks again
 * when the command arrives.
 */
export type Readiness = {
/**
 * Connect to the controller.
 */
connect: Gate,
/**
 * Go Origin.
 */
home: Gate,
/**
 * Head calibration.
 */
calibrate: Gate,
/**
 * Manual X/Y or configured table jogging using the controller's limits.
 */
jog: Gate,
/**
 * X then Y, each negative then positive, including limit recovery.
 */
xy_jog: [[Gate, Gate], [Gate, Gate]],
/**
 * X/Y presses are bounded to 1 mm at no more than 1 mm/s during recovery.
 */
xy_recovery: boolean,
/**
 * Manual Z up, including recovery from a lower limit.
 */
head_up: Gate,
/**
 * Manual Z down, including recovery from an upper limit.
 */
head_down: Gate,
/**
 * Z presses are bounded to 1 mm at no more than 1 mm/s during recovery.
 */
head_recovery: boolean,
/**
 * Move to an absolute job origin or bed point under matched parameters.
 */
position: Gate,
/**
 * Hold a manual output.
 */
outputs: Gate,
/**
 * Set the job origin where the head is.
 */
set_origin: Gate,
/**
 * Compile the draft.
 */
compile: Gate,
/**
 * Run the compiled draft.
 */
run: Gate,
/**
 * Resume the held program.
 */
resume: Gate,
/**
 * Hold the running program.
 */
hold: Gate,
/**
 * The stop sequence.
 */
stop: Gate,
/**
 * Switch the laser mode.
 */
mode: Gate,
/**
 * Trace the job's bounds with the laser off.
 */
frame: Gate, };
