// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The headline process values of a recipe.
 */
export type RecipeSummary = { 
/**
 * `CutSpeed` in millimetres per second.
 */
speed: string | null, 
/**
 * `CutPower` in percent.
 */
power: string | null, 
/**
 * `CutAirPressure` in bar.
 */
pressure: string | null, 
/**
 * `CutHeight` in millimetres.
 */
height: string | null, 
/**
 * `CutFreq` in hertz.
 */
frequency: string | null, 
/**
 * `CutGasType`, the gas selection 0 to 5.
 */
gas: string | null, };
