// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Id } from "./Id";

/**
 * A change to a recipe.
 */
export type RecipeChange = { 
/**
 * Saved values when these staged attributes were first edited.
 */
expected_attributes?: { [key in string]: string | null }, 
/**
 * Saved film choice when the staged edit began.
 */
expected_film?: Id | null, 
/**
 * The material.
 */
name?: string, 
/**
 * The sheet thickness.
 */
thickness_mm?: number, 
/**
 * The assist gas.
 */
gas?: string, 
/**
 * Starred or not.
 */
favourite?: boolean, 
/**
 * The note.
 */
note?: string, 
/**
 * The film process; `Some(None)` clears it.
 */
film?: Id | null, 
/**
 * Attribute values to replace.
 */
attributes: { [key in string]: string }, };
