// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Id } from "./Id";
import type { LaserMode } from "./LaserMode";
import type { RecipeSummary } from "./RecipeSummary";

/**
 * A recipe with the fields the operator reads off a card.
 */
export type RecipeView = { 
/**
 * Its id.
 */
id: Id, 
/**
 * The material.
 */
name: string, 
/**
 * Which laser.
 */
laser: LaserMode, 
/**
 * The sheet thickness.
 */
thickness_mm: number, 
/**
 * The assist gas.
 */
gas: string, 
/**
 * The vendor layer bank.
 */
layer: number, 
/**
 * The key jobs share features by.
 */
key: string, 
/**
 * The recipe the film pass runs with, when film removal is on.
 */
film: Id | null, 
/**
 * Cutting speed, power, pressure and height, as the vendor stores them.
 */
summary: RecipeSummary, 
/**
 * Every attribute, for the editor.
 */
attributes: { [key in string]: string }, 
/**
 * The vendor's note.
 */
note: string, 
/**
 * The process words from the vendor's file name.
 */
tags: Array<string>, 
/**
 * The file it was imported from.
 */
file_name: string | null, 
/**
 * The hash of its sample cut photo, served at `/api/photos/{hash}`.
 */
photo: string | null, 
/**
 * Whether it is starred.
 */
favourite: boolean, 
/**
 * When it last changed.
 */
updated: number, };
