// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HeadSetup } from "./HeadSetup";
import type { Id } from "./Id";
import type { LaserMode } from "./LaserMode";
import type { RecipeSummary } from "./RecipeSummary";

/**
 * What a vendor recipe file would add, for the operator to review before
 * anything is saved.
 */
export type RecipePreview = {
/**
 * The file's name.
 */
file_name: string,
/**
 * The material read from the name, or the whole name.
 */
name: string,
/**
 * Which laser the bank is for.
 */
laser: LaserMode,
/**
 * The sheet thickness read from the name, 0 when it is not there.
 */
thickness_mm: number,
/**
 * The assist gas, named as the library names it.
 */
gas: string,
/**
 * The vendor layer bank.
 */
layer: number,
/**
 * The process words from the name.
 */
tags: Array<string>,
/**
 * The vendor's note.
 */
note: string,
/**
 * The nozzle, focus and lens read from the note and names.
 */
setup: HeadSetup,
/**
 * The headline values.
 */
summary: RecipeSummary,
/**
 * The file's hash.
 */
sha256: string,
/**
 * A recipe already imported from these exact bytes.
 */
existing: Id | null, };
