// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Checkpoint } from "./Checkpoint";
import type { ProgramState } from "./ProgramState";
import type { RecoveryStep } from "./RecoveryStep";

/**
 * Recovery state for the original job, independent of a mutable draft.
 */
export type RecoveryView = {
/**
 * Revision required when changing a selection.
 */
revision: number,
/**
 * Original execution identity.
 */
id: number,
/**
 * Original job name.
 */
name: string,
/**
 * Current program state.
 */
state: ProgramState,
/**
 * Whether stopped-job preparation is still needed.
 */
ready: boolean,
/**
 * Selected original pass/fraction.
 */
selected: Checkpoint | null,
/**
 * Selected position in machine coordinates.
 */
position: [number, number] | null,
/**
 * Last settled pause position.
 */
last_pause: Checkpoint | null,
/**
 * Exact settled machine XY, retained while the operator moves the head.
 */
pause_position: [number, number] | null,
/**
 * Operator's known-good point.
 */
good: Checkpoint | null,
/**
 * Original pass statuses, including skipped physical contours.
 */
steps: Array<RecoveryStep>,
/**
 * A checkpoint that could not be located, requiring explicit selection.
 */
problem: string | null, };
