// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PassView } from "./PassView";

/**
 * One original pass and its observed execution intervals.
 */
export type RecoveryStep = {
/**
 * Original process and physical instances.
 */
pass: PassView,
/**
 * Length of its executed polyline; zero for preliminary points.
 */
length_mm: number,
/**
 * Pending, partial, completed or skipped.
 */
status: string,
/**
 * Observed intervals as fractions of the original path.
 */
executed: Array<[number, number]>, };
