// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A selection change never sends a machine command.
 */
export type RecoveryChange = { "kind": "select", 
/**
 * The original pass index.
 */
pass: number, 
/**
 * Fraction of its executed path.
 */
fraction: number, } | { "kind": "previous" } | { "kind": "next" } | { "kind": "backward", 
/**
 * Distance in millimetres.
 */
distance: number, } | { "kind": "forward", 
/**
 * Distance in millimetres.
 */
distance: number, } | { "kind": "skip" } | { "kind": "include_all" } | { "kind": "last_pause" } | { "kind": "mark_good" } | { "kind": "last_good" };
