// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What relieving an alarm does.
 */
export type ReliefView = {
/**
 * Operator-facing action name.
 */
label: string,
/**
 * Whether the action can command axis movement.
 */
moves_axes: boolean, };
