// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A reset result kept as history, never an acknowledgement requirement.
 */
export type ResetRecord = {
/**
 * Time the attempt finished.
 */
at: number,
/**
 * Whether the controller operation succeeded.
 */
ok: boolean,
/**
 * Failure detail, if the operation failed.
 */
error: string | null, };
