// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A change to the route from the Settings page: an adapter chosen among
 * several, or another address for the controller or the computer. Kept
 * for the next Connect.
 */
export type RouteChange = {
/**
 * Saved field values from which these edits started.
 */
expected?: { [key in string]: string },
/**
 * The adapter to use, by name.
 */
adapter?: string,
/**
 * The controller's endpoint, `ip:port`.
 */
controller?: string,
/**
 * The computer's address on the controller's network, `ip/prefix`.
 */
host?: string, };
