// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One host input rule.
 */
export type RuleView = { 
/**
 * The vendor's id.
 */
id: number, 
/**
 * The label.
 */
label: string, 
/**
 * The input.
 */
input: number, };
