// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Consumption } from "./Consumption";
import type { Id } from "./Id";
import type { RunOutcome } from "./RunOutcome";

/**
 * One run of a job and what it spent.
 */
export type RunRecord = {
/**
 * Stable identity.
 */
id: string,
/**
 * The authoring document it ran from, as `job-…`, `draft-…` or `part-…`.
 */
key: string,
/**
 * The saved job, if it was one.
 */
job: Id | null,
/**
 * The job's name when it ran.
 */
name: string,
/**
 * When it started, in seconds since the epoch.
 */
started: number,
/**
 * When it last ended.
 */
finished: number,
/**
 * Done or stopped.
 */
outcome: RunOutcome,
/**
 * The share of the job's cut length that ran, 0 to 1.
 */
fraction: number,
/**
 * Laser time, gas and cost of what ran, priced when it ended.
 */
consumption: Consumption,
/**
 * The currency symbol it was priced in.
 */
currency: string, };
