// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Bounds } from "./Bounds";

/**
 * Operator confirmation and optional corrected rectangular stock size.
 */
export type SaveRemnant = { 
/**
 * Revision being inspected.
 */
revision: number, 
/**
 * Name on the stock card.
 */
name: string, 
/**
 * Replace an inferred boundary with the actual rectangular sheet bounds.
 */
bounds: Bounds | null, };
