// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SvgScale } from "./SvgScale";
import type { SvgUnits } from "./SvgUnits";

/**
 * How an SVG's size was read.
 */
export type ScaleReview = {
/**
 * How the document declares its size.
 */
units: SvgUnits,
/**
 * The scale applied to its pixels; absent when it is in real units.
 */
scale: SvgScale | null, };
