// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Millimeters } from "./Millimeters";

/**
 * How a closed contour's seam, where the cut ends where it began, is cut.
 */
export type Seam = "seal" | { "gap": Millimeters } | { "overcut": Millimeters };
