// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A duration in seconds, for accumulated machine time.
 */
export type Seconds = number;
