// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LaserMode } from "./LaserMode";
import type { Quality } from "./Quality";

/**
 * The authority facts of the connection.
 */
export type SessionView = { 
/**
 * Whether Go Origin established the XY reference on this connection.
 */
homed: boolean, 
/**
 * The mode applied on this connection.
 */
mode: LaserMode | null, 
/**
 * Whether the parameter banks were read back and matched.
 */
parameters_verified: boolean, 
/**
 * The head calibration made on this connection.
 */
calibration: Quality | null, };
