// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Id } from "./Id";

/**
 * Stable grouping for individual sheet jobs saved together.
 */
export type SheetInfo = { 
/**
 * Identity of the set's original folder.
 */
set: Id, 
/**
 * One-based sheet number.
 */
number: number, 
/**
 * Total sheets when saved.
 */
total: number, };
