// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SheetView } from "./SheetView";

/**
 * A page of sheet history, newest first.
 */
export type SheetPage = { 
/**
 * Records on this page.
 */
items: Array<SheetView>, 
/**
 * Cursor for older records.
 */
next: string | null, };
