// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One sheet, width along X by height along Y, in millimetres.
 */
export type SheetSize = {
/**
 * Along X.
 */
width_mm: number,
/**
 * Along Y.
 */
height_mm: number, };
