// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Bounds } from "./Bounds";
import type { Id } from "./Id";
import type { LaserMode } from "./LaserMode";
import type { SheetState } from "./SheetState";

/**
 * An inspected sheet or completion record, with display geometry only.
 */
export type SheetView = {
/**
 * Stable sheet identity.
 */
id: string,
/**
 * Concurrency token for edits.
 */
revision: number,
/**
 * Completed, interrupted or inspected state.
 */
state: SheetState,
/**
 * Already reserved by a later cut; cannot be selected as stock again.
 */
used: boolean,
/**
 * Operator's name.
 */
name: string,
/**
 * Original saved job, when one exists.
 */
job: Id | null,
/**
 * Process used on this sheet.
 */
mode: LaserMode,
/**
 * Material name.
 */
material: string,
/**
 * Thickness in millimetres.
 */
thickness_mm: number,
/**
 * Recording time in Unix seconds.
 */
at: number,
/**
 * Marked cut by an operator instead of a controller completion.
 */
reported: boolean,
/**
 * Whether a stock outline was specified before the job.
 */
boundary_known: boolean,
/**
 * Outer stock extent.
 */
bounds: Bounds,
/**
 * Outer boundary for the sheet viewer.
 */
outline: Array<[number, number]>,
/**
 * Reserved removed regions for the viewer.
 */
cutouts: Array<Array<[number, number]>>,
/**
 * Inherited minimum margin for prior kerf and leads, in millimetres.
 */
clearance: number,
/**
 * The library folder a remnant is kept in, or the root.
 */
folder: Id | null, };
