// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SheetTab } from "./SheetTab";

/**
 * Small navigation data; only the active sheet sends prepared canvas geometry.
 */
export type SheetNavigation = { 
/**
 * Zero-based selected entry.
 */
active: number, 
/**
 * Sheets in numbered order.
 */
pages: Array<SheetTab>, };
