// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Material state, independent of any later job edits.
 */
export type SheetState = "cutting" | "completed" | "interrupted" | "remnant";
