// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Id } from "./Id";

/**
 * One numbered entry in the sheet switcher.
 */
export type SheetTab = {
/**
 * One-based sheet number.
 */
number: number,
/**
 * Physical part count, absent when opening a saved job without preparation.
 */
parts: number | null,
/**
 * Saved job identity, absent until the set is saved.
 */
job: Id | null, };
