// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which side of a contour something lies on.
 */
export type Side = "auto" | "inside" | "outside";
