// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Id } from "./Id";

/**
 * What simplifying a part's drawing does, and the part it made once saved.
 */
export type SimplifyView = {
/**
 * Lines and arcs before.
 */
curves_before: number,
/**
 * Lines and arcs after.
 */
curves_after: number,
/**
 * Contours before.
 */
contours_before: number,
/**
 * Contours after.
 */
contours_after: number,
/**
 * Contours dropped for repeating another on the same layer.
 */
repeats: number,
/**
 * Contours dropped for being smaller than the tolerance.
 */
specks: number,
/**
 * The simplified part, once saved.
 */
part: Id | null, };
