// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether the drawing's size is plausible for this machine.
 */
export type SizeCheck = { 
/**
 * The width and height of the drawing, in millimetres.
 */
size: [number, number], 
/**
 * The width and height of the bed, when the machine is known.
 */
bed: [number, number] | null, 
/**
 * Larger than the bed, turned either way, or than any bed when none is
 * known.
 */
exceeds_bed: boolean, 
/**
 * So small that its units are probably wrong.
 */
tiny: boolean, };
