// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A library file that could not be loaded, and why.
 */
export type SkippedView = {
/**
 * The file, relative to the data directory.
 */
file: string,
/**
 * Why it was left out.
 */
reason: string, };
