// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A compact projection of the imported Soft INI.
 */
export type SoftView = {
/**
 * Original filename, if imported.
 */
name: string | null,
/**
 * Hash of the exact source bytes.
 */
sha256: string | null,
/**
 * Follow/retract timeout in milliseconds.
 */
follow_ms: number,
/**
 * Pierce-height timeout in milliseconds.
 */
section_drill_ms: number,
/**
 * Minimum nonzero analog peak request.
 */
analog_minimum: number, };
