// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CubicMeters } from "./CubicMeters";
import type { Money } from "./Money";

/**
 * Where a gas comes from and what it costs.
 */
export type Source = { "kind": "refill", 
/**
 * The price of one refill; zero until the shop enters it.
 */
price: Money, 
/**
 * The gas one cylinder holds at standard conditions.
 */
volume: CubicMeters, } | { "kind": "bulk", 
/**
 * The price per standard cubic metre.
 */
price_per_m3: Money, } | { "kind": "compressor", 
/**
 * Running cost per hour.
 */
cost_per_hour: Money, };
