// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A place along a drawing contour: the contour's index in the drawing and
 * the fraction of its length, as drawn.
 */
export type Spot = {
/**
 * The contour.
 */
contour: number,
/**
 * How far along it, 0 to 1.
 */
fraction: number, };
