// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Direction } from "./Direction";
import type { Spot } from "./Spot";
import type { StartPosition } from "./StartPosition";

/**
 * Where each contour starts and which way it runs.
 */
export type Start = {
/**
 * Where cutting starts.
 */
position: StartPosition,
/**
 * Which way the cut runs.
 */
direction: Direction,
/**
 * Starts chosen on the drawing, one per contour, over the position.
 */
spots: Array<Spot>, };
