// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a contour's cut starts.
 */
export type StartPosition = "keep" | "automatic" | { "manual": number };
