// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AlarmView } from "./AlarmView";
import type { Connection } from "./Connection";
import type { Feedback } from "./Feedback";
import type { Identity } from "./Identity";
import type { LaserMode } from "./LaserMode";
import type { OperationView } from "./OperationView";
import type { ProgramView } from "./ProgramView";
import type { SessionView } from "./SessionView";

/**
 * The published state.
 */
export type State = {
/**
 * Changes on alarm transitions or a controller link fault.
 */
alarm_revision: number,
/**
 * Changes with every publication.
 */
revision: number,
/**
 * The connection.
 */
connection: Connection,
/**
 * The controller's identity, once read.
 */
identity: Identity | null,
/**
 * The mode the bindings are for, once configured.
 */
configured_mode: LaserMode | null,
/**
 * The feedback, while connected.
 */
feedback: Feedback | null,
/**
 * The authority facts.
 */
session: SessionView,
/**
 * The alarm rows.
 */
alarms: Array<AlarmView>,
/**
 * Why operations are refused right now, if they are.
 */
blocked: string | null,
/**
 * The active operation.
 */
operation: OperationView | null,
/**
 * The last program.
 */
program: ProgramView | null,
/**
 * The last failure, until the next successful command.
 */
last_error: string | null, };
