// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A stock choice is a separate, undoable authoring edit.
 */
export type StockChoice = { "kind": "remnant", 
/**
 * Sheet library identity.
 */
id: string, } | { "kind": "rectangle", 
/**
 * Width in millimetres.
 */
width: number, 
/**
 * Height in millimetres.
 */
height: number, } | { "kind": "outline", 
/**
 * Placed contour index.
 */
contour: number, } | { "kind": "clear" };
