// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Id } from "./Id";
import type { LaserMode } from "./LaserMode";

/**
 * One size of full sheet in one material, and how many are on hand.
 */
export type StockItem = {
/**
 * Stable identity.
 */
id: Id,
/**
 * Material name, as the recipes name it.
 */
material: string,
/**
 * Thickness in millimetres.
 */
thickness_mm: number,
/**
 * The laser its recipes are for.
 */
laser: LaserMode,
/**
 * Along X, in millimetres.
 */
width_mm: number,
/**
 * Along Y, in millimetres.
 */
height_mm: number,
/**
 * Sheets on hand; zero keeps the size listed for restocking.
 */
quantity: number,
/**
 * The library folder it is kept in, beside its jobs, or the root.
 */
folder: Id | null, };
