// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Id } from "./Id";

/**
 * A change to one entry; absent fields stay as they are.
 */
export type StockChange = {
/**
 * Sheets on hand.
 */
quantity?: number,
/**
 * Move to this folder; `Some(None)` moves it to the root.
 */
folder?: Id | null, };
