// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Id } from "./Id";

/**
 * One kind of sheet a search may fill. Sheets fill in the order listed,
 * so remnants usually come first.
 */
export type StockSource = { "kind": "sheet",
/**
 * Width in millimetres.
 */
width: number,
/**
 * Height in millimetres.
 */
height: number,
/**
 * At most this many.
 */
count: number, } | { "kind": "stock",
/**
 * Inventory entry.
 */
id: Id,
/**
 * Sheets to use at most.
 */
count: number, } | { "kind": "remnant",
/**
 * Sheet library identity.
 */
id: string, };
