// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Calibration } from "./Calibration";
import type { Flow } from "./Flow";
import type { Source } from "./Source";

/**
 * The shop's supply of one gas.
 */
export type Supply = {
/**
 * Where it comes from and its price.
 */
source: Source,
/**
 * How its flow is known.
 */
flow: Flow,
/**
 * The latest flow test, if one was saved.
 */
calibration: Calibration | null, };
