// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GasKind } from "./GasKind";
import type { Money } from "./Money";

/**
 * One gas's derived figures for the settings page.
 */
export type SupplyView = {
/**
 * Which gas.
 */
gas: GasKind,
/**
 * The price per standard cubic metre, when priced by volume.
 */
price_per_m3: Money | null, };
