// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How many pixels of a pixel-sized SVG make an inch, or a millimetre.
 */
export type SvgScale = "dpi96" | "dpi72" | "millimetre";
