// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Who sized an SVG, and so how its pixels were read.
 */
export type SvgUnits = "physical" | "illustrator" | "inkscape" | "ambiguous";
