// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A held W/table jog at an operator-selected speed.
 */
export type TableRequest = { 
/**
 * Positive or negative W travel.
 */
positive: boolean, 
/**
 * A speed above zero and at most 100 mm/s.
 */
speed_mm_s: number, };
