// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A uniform similarity transform as an affine matrix `[a, b, c, d, e, f]`:
 * `x' = a·x + c·y + e`, `y' = b·x + d·y + f`. Rotation, mirroring and
 * translation and uniform scale, so circles remain circles.
 */
export type Transform = [number, number, number, number, number, number];
