// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GasTime } from "./GasTime";
import type { Millimeters } from "./Millimeters";
import type { Seconds } from "./Seconds";

/**
 * What a program, or a part of it, spends: laser time, gas time per gas
 * and pressure, pierces and cut length.
 */
export type Usage = {
/**
 * Time the laser output is on.
 */
laser: Seconds,
/**
 * Gas valve time, one entry per gas and pressure.
 */
gases: Array<GasTime>,
/**
 * How many times the program pierces.
 */
pierces: number,
/**
 * Length cut with the beam on, leads included.
 */
cut: Millimeters, };
