// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Id } from "./Id";

/**
 * Where a new recipe's values come from.
 */
export type Values = { "bank": number } | { "recipe": Id };
